title: Gecko Research
description: Financial research reports by Gecko

remote_theme: jekyll/theme-slate

plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/awaysooner/brain" }